### ISSUE TITLE
Shutdown the DVR

### ISSUE THREAD

**Issue by Vladdrako** [667bdrm/sofiactl#4]
Hi. Can I shutdown the DVR via sofiactl? I have OpenWrt-based Wi-Fi router with UPS connected to USB via Network Ups Tools. I want to automate shutdown. OpenWrt will send shutdown command to DVR, then power off UPS.

**Comment by 667bdrm** [comment]
Hi. I don't know if the device Sofia api support shutdown. I only seen the reboot schedule option in the CMS app. If you have root password of the DVR linux you could try to authenticate and execute 'halt' shell command from the OpenWRT, but it could not have effect if the device does not have implemented the shutdown functionality. [Here](https://gist.github.com/667bdrm/9217f0e46814915a14f567a9127c63fa) is a list of known DVR linux passwords. Otherwise you need to have DVR power connected through managed relay (for example Arduino or ESP8266 based).

**Comment by 667bdrm** [comment]
Update:

Just checked with the new camera:

/sbin/halt and /sbin/poweroff  killing telnet session, the device not answering to pings, but after timeout the device become visible and accessible by telnet. Looks like it rebooting after these commands.
