### ISSUE TITLE
ChannelTitleSet, help me!

### ISSUE THREAD

**Issue by Wifibus** [667bdrm/sofiactl#6]
Hello friend, what is the correct form of the command to change the title of the channel. ? ChannelTitleSet, help me!

**Comment by vladisslav2011** [comment]
This from works to me after fixing a bug in https://github.com/vladisslav2011/sofiactl/commit/8ecc885f40648564b4366a38e38663fd34292bb0:
./sofiactl.pl -host 192.168.1.2 -port 34567 -u admin -c ChannelTitleSet -sd "New title"

**Comment by 667bdrm** [comment]
Yes, that works. Merged to master. Thank You!
Note: If you have more than 1 channel you must specity all channel titles with comma, otherwise title will be setted to channel 1 and all other titles will be set to empty values. I.e.:

./sofiactl.pl -host 192.168.1.2 -port 34567 -u admin -c ChannelTitleSet -sd "ROAD,BACKYARD,PARKING,GATE,DOOR,HALL"
